name: Conscious Creative
favicon: null
layout_spectrum: 0.41653
typography_spectrum: 0.66861
title: Conscious Creative
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6422688686288893
  lightness: 0.9388718795962632
  saturation: 0.7870151652023196
  rhythmicContrast: 0.9145199267659336
purpose: []
