name: Conscious Creative
favicon: null
layout_spectrum: 0.41653
typography_spectrum: 0.66861
title: Conscious Creative
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#59a4cf'
    - '#241a19'
    - '#2e90c4'
    - '#29354b'
    - '#295c83'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.9145199267659336
purpose: []
